### ISSUE TITLE
CR: Scatter Plot of GDP Growth vs Average Fertility Rate 

### ISSUE THREAD

**Issue by philippaSteinberg** [nkim02/Quetelet-Project-1#11]
For `# Scatter Plot of GDP Growth vs Average Fertility Rate` I would not write the interpretation into the figure title. Additionally, I do not know if your plat actually shows that _Periods of Higher GDP Growth Tend to Have Higher Fertility_. One way to maybe emphasize this hypothesis is to make each year its own point on the scatterplot and create a line of best fit. It is really hard to make inference over 20 year periods of time.

**Comment by lchambadal** [comment]
We are not using this plot!
